name:                ApiTemplate
version:             0.1.0.0
github:              cackharot/haskell-web-api-template
license:             MIT
author:              Cackharot
maintainer:          cackharot@gmail.com
copyright:           2020 Cackharot

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/cackharot/haskell-web-api-template#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.14.0
- time
- text >= 1.2.3.1
- mtl >= 2.2.2
- data-default >= 0.7.1.1
- data-has
- bytestring >= 0.10.8.2 
- unordered-containers >= 0.2.10.0
- transformers >= 0.5.6.2
- dotenv >= 0.8.0.4
- envy >= 2.0.0.0
- aeson >= 1.4.6.0
- http-types >= 0.12.3
- warp >= 3.3.5
- wai >= 3.2.2.1
- wai-extra
- wai-cli
- prometheus-client >= 1.0.0
- wai-middleware-prometheus >= 1.0.0
- prometheus-metrics-ghc >= 1.0.1.1
- servant-server >= 0.18.2
- fast-logger >= 2.4.17

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ApiTemplate-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - ApiTemplate
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T

tests:
  ApiTemplate-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - ApiTemplate
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
